package com.smily.bean;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
	 * @mbggenerated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.role
	 * @mbggenerated
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.salt
	 * @mbggenerated
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password_str
	 * @mbggenerated
	 */
	private String passwordStr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
	 * @return  the value of users.username
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.username
	 * @param username  the value for users.username
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.role
	 * @return  the value of users.role
	 * @mbggenerated
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.role
	 * @param role  the value for users.role
	 * @mbggenerated
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.salt
	 * @return  the value of users.salt
	 * @mbggenerated
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.salt
	 * @param salt  the value for users.salt
	 * @mbggenerated
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password_str
	 * @return  the value of users.password_str
	 * @mbggenerated
	 */
	public String getPasswordStr() {
		return passwordStr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password_str
	 * @param passwordStr  the value for users.password_str
	 * @mbggenerated
	 */
	public void setPasswordStr(String passwordStr) {
		this.passwordStr = passwordStr;
	}
}